base_url = "https://www.cs.cornell.edu/courses/cs6120/2022sp"
compile_sass = true
build_search_index = false

generate_feed = true
feed_filename = "rss.xml"

highlight_code = true
highlight_theme = "subway-madrid"

title = "CS 6120"

[extra]
favicon = "/img/favicon.ico"
bigicon = "/img/favicon152.png"

[[extra.links]]
name = "Zulip"
url = "https://cs6120.zulipchat.com"
